POST http://localhost:3002/api/calendars/620919843d67af91bdcd29f4/events
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNjFmMDExZjRkOWUzZjUyZDI0NWQwMGYxIiwiaWF0IjoxNjQzMTIzMjEyfQ.eZrwAd1AOydZcDnpC9wK1p18KBX8cFuftTWNY0gil18

{
  "name": "test_event",
  "date": "2022-02-14T21:00:00.000+00:00",
  "end": "2022-02-14T23:00:00.000+00:00",
  "users": ["620919843d67af91bdcd29f4", "61f011ffd9e3f52d245d00f5", "6205baa745be0798bd2f7b0b"]
}
